'use server'

import axios from '@custom-axios/peta-fetcher'

export const getSpjFungsionalSipdPeta = async ({
   id_pegawai = 0,
   bulan,
   type,
}: {
   type: string
   bulan: string
   id_pegawai?: number
}) => {
   return await axios.get<SpjFungsionalSipdPeta>(`pengeluaran/strict/lpj/adm-fungs/0`, {
      params: { id_pegawai, bulan, type },
   })
}

export async function testPenugasanPPTK() {
   const kegiatan = [
      {
         id_pelimpahan_kpa: 0,
         id_penugasan: 0,
         id_daerah: 424,
         tahun: 2024,
         id_urusan: 12,
         id_bid_urusan: 211,
         id_fungsi: 4,
         id_sub_fungsi: 20,
         id_unit: 1871,
         id_skpd: 1871,
         kode_skpd: '2.11.0.00.0.00.01.0000',
         nama_skpd: 'DINAS LINGKUNGAN HIDUP',
         id_sub_skpd: 1871,
         kode_sub_skpd: '2.11.0.00.0.00.01.0000',
         nama_sub_skpd: 'DINAS LINGKUNGAN HIDUP',
         id_program: 1068,
         kode_program: '2.11.03',
         nama_program: 'PROGRAM PENGENDALIAN PENCEMARAN DAN/ATAU KERUSAKAN LINGKUNGAN HIDUP',
         id_giat: 8262,
         kode_giat: '2.11.03.2.01',
         nama_giat: 'Pencegahan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota',
         id_sub_giat: 0,
         kode_sub_giat: '',
         nama_sub_giat: '',
         subs_bl_teks: '',
         id_akun: 0,
         kode_akun: '',
         nama_akun: '',
         id_pegawai_pa: 0,
         nama_pegawai_pa: 'Christianus Rimbaraya, SE, MM',
         id_pegawai_pa_kpa: 0,
         nama_pegawai_pa_kpa: '',
         id_pegawai_pptk: 6261,
         nama_pegawai_pptk: 'RASYID ABD. JALAL, S.Si',
         nilai: 495587608,
         // sub_giat: [],
         frontend_id: '12-211---2.11.03.2.01-495587608',
      },
      {
         id_pelimpahan_kpa: 0,
         id_penugasan: 0,
         id_daerah: 424,
         tahun: 2024,
         id_urusan: 12,
         id_bid_urusan: 211,
         id_fungsi: 4,
         id_sub_fungsi: 20,
         id_unit: 0,
         id_skpd: 1871,
         kode_skpd: '',
         nama_skpd: '',
         id_sub_skpd: 0,
         kode_sub_skpd: '',
         nama_sub_skpd: '',
         id_program: 1068,
         kode_program: '',
         nama_program: '',
         id_giat: 8263,
         kode_giat: '2.11.03.2.02',
         nama_giat: 'Penanggulangan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota',
         id_sub_giat: 0,
         kode_sub_giat: '',
         nama_sub_giat: '',
         subs_bl_teks: '',
         id_akun: 0,
         kode_akun: '',
         nama_akun: '',
         id_pegawai_pa: 0,
         nama_pegawai_pa: 'Christianus Rimbaraya, SE, MM',
         id_pegawai_pa_kpa: 0,
         nama_pegawai_pa_kpa: '',
         id_pegawai_pptk: 6261,
         nama_pegawai_pptk: '',
         nilai: 173423175,
         sub_giat: [],
         frontend_id: '12-211---2.11.03.2.02-173423175',
      },
      {
         id_pelimpahan_kpa: 0,
         id_penugasan: 0,
         id_daerah: 424,
         tahun: 2024,
         id_urusan: 12,
         id_bid_urusan: 211,
         id_fungsi: 4,
         id_sub_fungsi: 20,
         id_unit: 0,
         id_skpd: 1871,
         kode_skpd: '',
         nama_skpd: '',
         id_sub_skpd: 0,
         kode_sub_skpd: '',
         nama_sub_skpd: '',
         id_program: 1068,
         kode_program: '',
         nama_program: '',
         id_giat: 8264,
         kode_giat: '2.11.03.2.03',
         nama_giat: 'Pemulihan Pencemaran dan/atau Kerusakan Lingkungan Hidup Kabupaten/Kota',
         id_sub_giat: 0,
         kode_sub_giat: '',
         nama_sub_giat: '',
         subs_bl_teks: '',
         id_akun: 0,
         kode_akun: '',
         nama_akun: '',
         id_pegawai_pa: 0,
         nama_pegawai_pa: 'Christianus Rimbaraya, SE, MM',
         id_pegawai_pa_kpa: 0,
         nama_pegawai_pa_kpa: '',
         id_pegawai_pptk: 6261,
         nama_pegawai_pptk: '',
         nilai: 12000000,
         sub_giat: [],
         frontend_id: '12-211---2.11.03.2.03-12000000',
      },
      {
         id_pelimpahan_kpa: 0,
         id_penugasan: 0,
         id_daerah: 424,
         tahun: 2024,
         id_urusan: 12,
         id_bid_urusan: 211,
         id_fungsi: 4,
         id_sub_fungsi: 18,
         id_unit: 0,
         id_skpd: 1871,
         kode_skpd: '',
         nama_skpd: '',
         id_sub_skpd: 0,
         kode_sub_skpd: '',
         nama_sub_skpd: '',
         id_program: 1069,
         kode_program: '',
         nama_program: '',
         id_giat: 8265,
         kode_giat: '2.11.04.2.01',
         nama_giat: 'Pengelolaan Keanekaragaman Hayati Kabupaten/Kota',
         id_sub_giat: 0,
         kode_sub_giat: '',
         nama_sub_giat: '',
         subs_bl_teks: '',
         id_akun: 0,
         kode_akun: '',
         nama_akun: '',
         id_pegawai_pa: 0,
         nama_pegawai_pa: 'Christianus Rimbaraya, SE, MM',
         id_pegawai_pa_kpa: 0,
         nama_pegawai_pa_kpa: '',
         id_pegawai_pptk: 6261,
         nama_pegawai_pptk: '',
         nilai: 3070475,
         sub_giat: [],
         frontend_id: '12-211---2.11.04.2.01-3070475',
      },
   ]
   const data = {
      items: [],
      id_pegawai_pptk: 6261,
      sub_kegiatan: [],
   }
   const defaultData = {
      id_unit: 1871,
      id_pegawai_pa: 0,
      nama_pegawai_pa: 'Christianus Rimbaraya, SE, MM',
      id_pegawai_pa_kpa: 4546,
      nama_pegawai_pa_kpa: '',
      id_pegawai_pptk: 6261,
      nama_pegawai_pptk: 'RASYID ABD. JALAL, S.Si',
      id_pelimpahan_kpa: 0,
      id_penugasan: 0,
      id_daerah: 424,
      tahun: 2024,
      id_urusan: 12,
      id_bid_urusan: 211,
      id_fungsi: 4,
      id_sub_fungsi: 20,
      id_skpd: 1871,
      kode_skpd: '2.11.0.00.0.00.01.0000',
      nama_skpd: 'DINAS LINGKUNGAN HIDUP',
      id_sub_skpd: 1871,
      kode_sub_skpd: '2.11.0.00.0.00.01.0000',
      nama_sub_skpd: 'DINAS LINGKUNGAN HIDUP',
      id_program: 1068,
      kode_program: '2.11.03',
      nama_program: 'PROGRAM PENGENDALIAN PENCEMARAN DAN/ATAU KERUSAKAN LINGKUNGAN HIDUP',
   }

   const newGiat = kegiatan?.map((d) => ({ ...d, ...defaultData }))
   const res = await axios.post<boolean>(`referensi/strict/penugasan`, {
      ...data,
      kegiatan: newGiat,
   })
   console.log(res)
}
