interface ListBlSubGiatBySubSkpdSipdPayload {
   id_daerah: number
   tahun: number
   id_sub_skpd: number
   id_skpd: number
}
interface BlSubGiatSipdPayload {
   id_daerah: number
   tahun: number
   id_sub_bl: number
   is_anggaran: number
   id_unit: number
   id_jadwal?: number
}
interface BlSubGiatBySkpdSipdPayload {
   id_daerah: number
   tahun: number
   id_skpd: number
   id_unit: number
}
interface BlSubGiatBySkpdSipdResponse {
   status: boolean
   status_code: number
   data: BlSubGiatSipd[]
}
interface BlSubGiatSipdResponse {
   status: boolean
   status_code: number
   data: BlSubGiatSipd[]
}

interface BlSubGiatSipd {
   created_at: string
   created_user: number
   id_bidang_urusan_pusat: number
   id_bidang_urusan: number
   id_bl: number
   id_daerah: number
   id_dana: number
   id_giat: number
   id_jadwal_murni: number
   id_jadwal?: number
   id_lokasi: number
   id_pptk: number
   id_program: number
   id_skpd: number
   id_sub_bl: number
   id_sub_giat: number
   id_sub_skpd: number
   id_unik: string
   id_unit: number
   id_urusan_pusat: number
   id_urusan: number
   kode_bidang_urusan_pusat: string
   kode_bidang_urusan: string
   kode_daerah: string
   kode_dana: string
   kode_giat: string
   kode_program: string
   kode_skpd: string
   kode_sub_giat: string
   kode_sub_skpd: string
   kode_unit: string
   kode_urusan_pusat: string
   kode_urusan: string
   kua_murni: number
   kua_pak: number
   kunci_akb_rinci_at: string
   kunci_bl_akb_user: number
   kunci_bl_akb: number
   kunci_bl_at: string
   kunci_bl_rinci_at: string
   kunci_bl_rinci_user: number
   kunci_bl_rinci: number
   kunci_bl_user: number
   kunci_bl: number
   migrated_at?: any
   nama_bidang_urusan_pusat: string
   nama_bidang_urusan: string
   nama_bl?: any
   nama_daerah: string
   nama_dana: string
   nama_giat: string
   nama_jadwal_murni: string
   nama_lokasi: string
   nama_pptk: string
   nama_program: string
   nama_skpd: string
   nama_sub_giat: string
   nama_sub_skpd: string
   nama_unit: string
   nama_urusan_pusat: string
   nama_urusan: string
   no_sub_giat: string
   output_teks: string
   pagu_indikatif: number
   pagu_n_depan: number
   pagu_n_lalu: number
   pagu_n2_depan: number
   pagu_n2_lalu: number
   pagu: number
   rkpd_murni: number
   rkpd_pak: number
   set_pagu_at: string
   set_pagu_user: number
   tahun: number
   total_rincian?: number
   updated_at: string
   updated_user: number
   waktu_akhir: number
   waktu_awal: number
}

interface RootObject {
   id_sub_bl: number
   id_unik: string
   tahun: number
   id_daerah: number
   id_unit: number
   id_skpd: number
   id_sub_skpd: number
   id_pptk: number
   id_urusan_pusat: number
   id_bidang_urusan_pusat: number
   id_urusan: number
   id_bidang_urusan: number
   id_program: number
   id_giat: number
   id_bl: number
   id_sub_giat: number
   no_sub_giat: string
   pagu: number
   id_dana: number
   id_lokasi: number
   waktu_awal: number
   waktu_akhir: number
   created_user: number
   created_at: string
   updated_user: number
   updated_at?: string
   pagu_indikatif: number
   set_pagu_user: number
   set_pagu_at?: string
   id_jadwal_murni: number
   output_teks: string
   pagu_n2_lalu: number
   pagu_n_lalu: number
   pagu_n_depan: number
   pagu_n2_depan: number
   kunci_bl: number
   kunci_bl_user: number
   kunci_bl_at?: string
   kunci_bl_rinci: number
   kunci_bl_rinci_user: number
   kunci_bl_rinci_at: string
   kunci_bl_akb: number
   kunci_bl_akb_user: number
   kunci_akb_rinci_at?: any
   rkpd_murni: number
   rkpd_pak: number
   nama_daerah: string
   nama_unit: string
   nama_skpd: string
   nama_sub_skpd: string
   nama_urusan: string
   nama_bidang_urusan: string
   nama_program: string
   nama_giat: string
   nama_bl?: any
   nama_sub_giat: string
   nama_pptk: string
   nama_urusan_pusat: string
   nama_bidang_urusan_pusat: string
   nama_dana: string
   nama_lokasi: string
   nama_jadwal_murni: string
   kua_murni: number
   kua_pak: number
   kode_daerah: string
   kode_unit: string
   kode_skpd: string
   kode_sub_skpd: string
   kode_urusan_pusat: string
   kode_urusan: string
   kode_bidang_urusan_pusat: string
   kode_bidang_urusan: string
   kode_program: string
   kode_giat: string
   kode_sub_giat: string
   kode_dana: string
   id_jadwal?: any
   migrated_at?: any
   total_rincian?: number
}
