import { z } from '../zod'

export const AkunBelanjaSchema = z.object({
   id: z.string().regex(/^[0-9a-fA-F]{24}$/, { message: 'bukan ObjectId' }),
   id_bidang_urusan: z.number().int(),
   id_daerah: z.number().int(),
   id_akun: z.number().int(),
   id_giat: z.number().int(),
   id_program: z.number().int(),
   id_rak_belanja: z.number().int().nullish(),
   id_skpd: z.number().int(),
   id_sub_giat: z.number().int(),
   id_sub_skpd: z.number().int(),
   id_unit: z.number().int(),
   id_urusan: z.number().int(),
   is_valid_bud: z.number().int(),
   is_valid_sekda: z.number().int(),
   is_valid_skpd: z.number().int(),
   kode_akun: z.string(),
   kode_bidang_urusan: z.string(),
   kode_giat: z.string(),
   kode_program: z.string(),
   kode_skpd: z.string(),
   kode_sub_giat: z.string(),
   kode_sub_skpd: z.string(),
   nama_akun: z.string(),
   nama_bidang_urusan: z.string(),
   nama_giat: z.string(),
   nama_program: z.string(),
   nama_skpd: z.string(),
   nama_sub_giat: z.string(),
   nama_sub_skpd: z.string(),
   tahun: z.number().int(),
   nilai: z.number().nullish(),
   nilai_rak: z.number().nullish(),
   nilai_realisasi: z.number().nullish(),
   bulan_1: z.number().nullish(),
   bulan_2: z.number().nullish(),
   bulan_3: z.number().nullish(),
   bulan_4: z.number().nullish(),
   bulan_5: z.number().nullish(),
   bulan_6: z.number().nullish(),
   bulan_7: z.number().nullish(),
   bulan_8: z.number().nullish(),
   bulan_9: z.number().nullish(),
   bulan_10: z.number().nullish(),
   bulan_11: z.number().nullish(),
   bulan_12: z.number().nullish(),
   realisasi_1: z.number().nullish(),
   realisasi_2: z.number().nullish(),
   realisasi_3: z.number().nullish(),
   realisasi_4: z.number().nullish(),
   realisasi_5: z.number().nullish(),
   realisasi_6: z.number().nullish(),
   realisasi_7: z.number().nullish(),
   realisasi_8: z.number().nullish(),
   realisasi_9: z.number().nullish(),
   realisasi_10: z.number().nullish(),
   realisasi_11: z.number().nullish(),
   realisasi_12: z.number().nullish(),
   created_by: z
      .string()
      .regex(/^[0-9a-fA-F]{24}$/, { message: 'bukan ObjectId' })
      .nullish(),
   created_at: z.coerce.date(),
   updated_by: z
      .string()
      .regex(/^[0-9a-fA-F]{24}$/, { message: 'bukan ObjectId' })
      .nullish(),
   updated_at: z.coerce.date(),
})

export const AkunBelanjaUncheckedCreateInputSchema = z
   .object({
      id: z
         .string()
         .regex(/^[0-9a-fA-F]{24}$/, { message: 'bukan ObjectId' })
         .optional(),
      id_bidang_urusan: z.number().int(),
      id_daerah: z.number().int(),
      id_akun: z.number().int(),
      id_giat: z.number().int(),
      id_program: z.number().int(),
      id_rak_belanja: z.number().int().optional().nullable(),
      id_skpd: z.number().int(),
      id_sub_giat: z.number().int(),
      id_sub_skpd: z.number().int(),
      id_unit: z.number().int(),
      id_urusan: z.number().int(),
      is_valid_bud: z.number().int().optional().nullable(),
      is_valid_sekda: z.number().int().optional().nullable(),
      is_valid_skpd: z.number().int().optional().nullable(),
      kode_akun: z.string(),
      kode_bidang_urusan: z.string(),
      kode_giat: z.string(),
      kode_program: z.string(),
      kode_skpd: z.string(),
      kode_sub_giat: z.string(),
      kode_sub_skpd: z.string(),
      nama_akun: z.string(),
      nama_bidang_urusan: z.string(),
      nama_giat: z.string(),
      nama_program: z.string(),
      nama_skpd: z.string(),
      nama_sub_giat: z.string(),
      nama_sub_skpd: z.string(),
      tahun: z.number().int(),
      nilai: z.number().optional().nullable(),
      nilai_rak: z.number().optional().nullable(),
      nilai_realisasi: z.number().optional().nullable(),
      bulan_1: z.number().optional().nullable(),
      bulan_2: z.number().optional().nullable(),
      bulan_3: z.number().optional().nullable(),
      bulan_4: z.number().optional().nullable(),
      bulan_5: z.number().optional().nullable(),
      bulan_6: z.number().optional().nullable(),
      bulan_7: z.number().optional().nullable(),
      bulan_8: z.number().optional().nullable(),
      bulan_9: z.number().optional().nullable(),
      bulan_10: z.number().optional().nullable(),
      bulan_11: z.number().optional().nullable(),
      bulan_12: z.number().optional().nullable(),
      realisasi_1: z.number().optional().nullable(),
      realisasi_2: z.number().optional().nullable(),
      realisasi_3: z.number().optional().nullable(),
      realisasi_4: z.number().optional().nullable(),
      realisasi_5: z.number().optional().nullable(),
      realisasi_6: z.number().optional().nullable(),
      realisasi_7: z.number().optional().nullable(),
      realisasi_8: z.number().optional().nullable(),
      realisasi_9: z.number().optional().nullable(),
      realisasi_10: z.number().optional().nullable(),
      realisasi_11: z.number().optional().nullable(),
      realisasi_12: z.number().optional().nullable(),
   })
   .strip()

declare global {
   type AkunBelanja = z.infer<typeof AkunBelanjaSchema>
   type AkunBelanjaUncheckedCreateInput = z.infer<typeof AkunBelanjaUncheckedCreateInputSchema>
}
